project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
  resources:
    - "files/"

execute:
  # Re-render only when source changes
  freeze: auto

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Independent readings course on Bayesian statistics at the Andrew Young School of Policy Studies at Georgia State University"

website:
  title: "Bayesian Statistics"
  #site-url: "https://bayessp23.classes.andrewheiss.com/"

  favicon: "/files/favicon.png"

  twitter-card:
    image: "https://bayessp23.classes.andrewheiss.com/files/social-image-sp23.png"
    card-style: summary_large_image
    creator: "@andrewheiss"
    # site: "@andrewheiss"

  open-graph:
    image: "https://bayessp23.classes.andrewheiss.com/files/social-image-sp23.png"
    locale: en_US

  repo-url: "https://github.com/andrewheiss/bayessp23.classes.andrewheiss.com"
  repo-actions: [edit, issue]

  page-navigation: true

  navbar:
    pinned: true
    background: primary
    right:
      - syllabus.qmd
      - schedule.qmd
      - resources.qmd
      - text: "My *Bayes Rules!* notebook"
        href: "https://bayesf22-notebook.classes.andrewheiss.com/bayes-rules/"
      - icon: github
        href: "https://github.com/andrewheiss/bayessp23.classes.andrewheiss.com"
        aria-label: GitHub

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} 2023 by Andrew Heiss<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/andrewheiss/bayessp23.classes.andrewheiss.com)


format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
